SportsStore/Components/AdminNavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace SportsStore.Components
{
    public class AdminNavigationMenuViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            this.ViewBag.Selection = this.Request.Path.Value ?? "Products";

            return this.View(new List<string> { "Orders", "Products" });
        }
    }
}

SportsStore/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;

namespace SportsStore.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private readonly Cart cart;

        public CartSummaryViewComponent(Cart cart)
        {
            this.cart = cart;
        }

        public IViewComponentResult Invoke()
        {
            return this.View(this.cart);
        }
    }
}

SportsStore/Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models.Repository;

namespace SportsStore.Components
{
  public class NavigationMenuViewComponent : ViewComponent
  {
        private readonly IStoreRepository repository;

        public NavigationMenuViewComponent(IStoreRepository repository)
        {
            this.repository = repository;
        }

        public IViewComponentResult Invoke()
        {
            this.ViewBag.SelectedCategory = this.RouteData?.Values["category"];
            return this.View(this.repository.Products
                   .Select(x => x.Category)
                   .Distinct()
                   .OrderBy(x => x));
        }
    }
}

SportsStore/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using SportsStore.Infrastructure;
using SportsStore.Models;
using SportsStore.Models.Repository;
using SportsStore.Models.ViewModels;

namespace SportsStore.Controllers
{
  public class CartController : Controller
    {
        private readonly IStoreRepository repository;
        private readonly IConfiguration configuration;

        public CartController(IStoreRepository repository, Cart cart, IConfiguration configuration)
        {
            this.repository = repository;
            this.Cart = cart;
            this.configuration = configuration;
        }

        public Cart Cart { get; set; }

        [HttpGet]
        public IActionResult Index(Uri returnUrl)
        {
            string applicationUrl = this.configuration["ApplicationSettings:DefaultReturnUrl"] ?? string.Empty;
            return this.View(new CartViewModel
            {
                ReturnUrl = returnUrl ?? new Uri(applicationUrl),
                Cart = this.HttpContext.Session.GetJson<Cart>("cart") ?? new Cart(),
            });
        }

        [HttpPost]
        public IActionResult Index(long productId, Uri returnUrl)
        {
            Product? product = this.repository.Products.FirstOrDefault(p => p.ProductId == productId);
            if (product != null)
            {
                this.Cart.AddItem(product, 1);
                string applicationUrl = this.configuration["ApplicationSettings:DefaultReturnUrl"] ?? string.Empty;
                ValidateDefaultUri(applicationUrl);
                return this.View(new CartViewModel
                {
                    Cart = this.Cart,
                    ReturnUrl = returnUrl ?? new Uri(applicationUrl),
                });
            }

            return this.RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [Route("Cart/Remove")]
        public IActionResult Remove(long productId, Uri returnUrl)
        {
            this.Cart.RemoveLine(this.Cart.Lines.First(cl => cl.Product.ProductId == productId).Product);
            string applicationUrl = this.configuration["ApplicationSettings:DefaultReturnUrl"] ?? string.Empty;
            ValidateDefaultUri(applicationUrl);
            return this.View("Index", new CartViewModel
            {
                Cart = this.Cart,
                ReturnUrl = returnUrl ?? new Uri(applicationUrl),
            });
        }

        private static void ValidateDefaultUri(string applicationUrl)
        {
            if (string.IsNullOrEmpty(applicationUrl))
            {
                throw new ArgumentNullException(nameof(applicationUrl));
            }
        }
    }
}

SportsStore/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SportsStore</title>
    <link href="/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="bg-info text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col">
                    <span class="navbar-brand ml-2">SPORTS STORE Administration</span>
                </div>
                <div class="col-2 text-right">
                    <a class="btn btn-sm btn-primary" asp-controller="Account" asp-action="Login">Log Out</a>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row p-2">
            <div class="col-3">
                <vc:admin-navigation-menu />
            </div>
            <div class="col-9">
                @RenderBody()
            </div>
        </div>
    </div>
    <script src="~/lib/jquery/jquery.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SportsStore/Views/Shared/_CartLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SportsStore</title>
    <link href="/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="bg-primary text-white p-2">
        <span class="navbar-brand ml-2">SPORTS STORE</span>
    </div>
    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>

SportsStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SportsStore</title>
    <link href="/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body>
    <div class="bg-primary text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand">SPORTS STORE</div>
                <div class="col-6 navbar-text text-end">
                    <vc:cart-summary />
                </div>
            </div>
        </div>
    </div>
    <div class="row m-1 p-1">
        <div id="categories" class="col-3">
            <vc:navigation-menu />
        </div>
        <div class="col-9">
            @RenderBody()
        </div>
    </div>
</body>
</html>

SportsStore/Views/Shared/_ProductSummary.cshtml
@model Product

<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model?.Name
            <span class="badge rounded-pill bg-primary text-white"
                  style="float:right">
                <small>@Model?.Price.ToString("c")</small>
            </span>
        </h4>
    </div>
    <form id="@Model?.ProductId" asp-controller="Cart" asp-antiforgery="true">
        <input type="hidden" asp-for="ProductId" />
        <input type="hidden" name="returnUrl"
               value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="card-text p-1">
            @Model?.Description
            <button type="submit"
                    class="btn btn-success btn-sm pull-right" style="float:right">
                Add To Cart
            </button>
        </span>
    </form>
</div>